name: CI - Build and Image Publish 

on: 
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        # server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        # settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build Jar with Gradle
      run: |
        cd aplicacoes/api
        ./gradlew build

    # - name: Obter versão do Jar
      # run: |
      #   echo API_VERSION=$(grep "^version" aplicacoes/api/gradle.properties | cut -d'=' -f2) >> $GITHUB_ENV
      #   echo $API_VERSION
      #   echo "${{ env.API_VERSION }}"

    # - name: Build API Docker image
    #   run: |
    #     docker build -t k8s-api:${{ env.API_VERSION }} .

    - name: Build API Docker image
      run: |
        docker build -t k8s-api:snapshot .

    # - name: conferir nome image
      # run: docker images | grep k8s
